[2025-10-10T08:37:46.852+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:37:46.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:37:46.890+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:37:46.889+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:37:47.032+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:37:47.004+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:37:47.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:37:47.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.385 seconds
[2025-10-10T08:38:17.587+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:38:17.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:38:17.597+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:38:17.596+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:38:17.643+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:38:17.632+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:38:17.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:38:17.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.125 seconds
[2025-10-10T08:38:48.001+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:38:48.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:38:48.050+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:38:48.048+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:38:48.250+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:38:48.215+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:38:48.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:38:48.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.468 seconds
[2025-10-10T08:39:19.271+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:39:19.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:39:19.280+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:39:19.280+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:39:19.329+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:39:19.319+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:39:19.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:39:19.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.154 seconds
[2025-10-10T08:39:49.782+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:39:49.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:39:49.796+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:39:49.795+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:39:49.859+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:39:49.845+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:39:49.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:39:49.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.170 seconds
[2025-10-10T08:40:20.595+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:40:20.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:40:20.605+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:40:20.604+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:40:20.647+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:40:20.637+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:40:20.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:40:20.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.117 seconds
[2025-10-10T08:40:50.884+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:40:50.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:40:50.893+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:40:50.893+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:40:50.932+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:40:50.925+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:40:50.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:40:50.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.120 seconds
[2025-10-10T08:41:21.100+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:41:21.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:41:21.111+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:41:21.110+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:41:21.212+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:41:21.188+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:41:21.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:41:21.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.238 seconds
[2025-10-10T08:41:52.013+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:41:52.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:41:52.022+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:41:52.021+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:41:52.063+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:41:52.054+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:41:52.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:41:52.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.115 seconds
[2025-10-10T08:42:22.425+0000] {processor.py:186} INFO - Started process (PID=632) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:42:22.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:42:22.445+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:42:22.444+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:42:22.558+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:42:22.532+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:42:22.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:42:22.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.293 seconds
[2025-10-10T08:42:53.209+0000] {processor.py:186} INFO - Started process (PID=695) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:42:53.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:42:53.225+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:42:53.224+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:42:53.283+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:42:53.269+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:42:53.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:42:53.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.167 seconds
[2025-10-10T08:43:23.973+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:43:23.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:43:23.985+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:43:23.984+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:43:24.048+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:43:24.035+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:43:24.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:43:24.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.157 seconds
[2025-10-10T08:43:54.308+0000] {processor.py:186} INFO - Started process (PID=821) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:43:54.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:43:54.322+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:43:54.321+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:43:54.380+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:43:54.368+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:43:54.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:43:54.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.185 seconds
[2025-10-10T08:44:25.034+0000] {processor.py:186} INFO - Started process (PID=883) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:44:25.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:44:25.049+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:44:25.048+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:44:25.084+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:44:25.077+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:44:25.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:44:25.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.115 seconds
[2025-10-10T08:44:55.568+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:44:55.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:44:55.600+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:44:55.597+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:44:55.659+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:44:55.649+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:44:55.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:44:55.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.195 seconds
[2025-10-10T08:45:25.871+0000] {processor.py:186} INFO - Started process (PID=1009) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:45:25.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:45:25.884+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:45:25.883+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:45:25.936+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:45:25.925+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:45:25.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:45:26.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.159 seconds
[2025-10-10T08:45:56.522+0000] {processor.py:186} INFO - Started process (PID=1072) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:45:56.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:45:56.533+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:45:56.532+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:45:56.582+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:45:56.571+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:45:56.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:45:56.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.126 seconds
[2025-10-10T08:46:27.511+0000] {processor.py:186} INFO - Started process (PID=1135) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:46:27.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:46:27.524+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:46:27.522+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:46:27.585+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:46:27.571+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:46:27.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:46:27.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.168 seconds
[2025-10-10T08:46:57.946+0000] {processor.py:186} INFO - Started process (PID=1198) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:46:57.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:46:57.956+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:46:57.955+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:46:57.996+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:46:57.986+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:46:57.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:46:58.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.114 seconds
[2025-10-10T08:47:28.840+0000] {processor.py:186} INFO - Started process (PID=1261) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:47:28.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:47:28.850+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:47:28.849+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:47:28.906+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:47:28.894+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:47:28.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:47:28.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.137 seconds
[2025-10-10T08:47:59.305+0000] {processor.py:186} INFO - Started process (PID=1324) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:47:59.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:47:59.327+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:47:59.326+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:47:59.465+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:47:59.436+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:47:59.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:47:59.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.324 seconds
[2025-10-10T08:48:29.822+0000] {processor.py:186} INFO - Started process (PID=1387) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:48:29.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:48:29.835+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:48:29.834+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:48:29.884+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:48:29.874+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:48:29.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:48:29.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.151 seconds
[2025-10-10T08:49:00.570+0000] {processor.py:186} INFO - Started process (PID=1450) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:49:00.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:49:00.580+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:49:00.579+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:49:00.622+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:49:00.613+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:49:00.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:49:00.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.124 seconds
[2025-10-10T08:53:42.739+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:53:42.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:53:42.756+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:53:42.755+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:53:42.808+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:53:42.794+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:53:42.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:53:42.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.187 seconds
[2025-10-10T08:54:13.641+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:54:13.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:54:13.652+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:54:13.651+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:54:13.705+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:54:13.689+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:54:13.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:54:13.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.173 seconds
[2025-10-10T08:54:44.853+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:54:44.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:54:44.935+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:54:44.931+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:54:45.079+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:54:45.011+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:54:45.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:54:45.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 1.153 seconds
[2025-10-10T08:57:53.375+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:57:53.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:57:53.388+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:57:53.387+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:57:53.439+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:57:53.426+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:57:53.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:57:53.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.160 seconds
[2025-10-10T08:58:24.590+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:58:24.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:58:24.643+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:58:24.627+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:58:24.795+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:58:24.773+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-10T08:58:24.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:58:24.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.328 seconds
[2025-10-10T08:58:36.911+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:58:36.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T08:58:36.919+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:58:36.919+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:58:36.997+0000] {logging_mixin.py:190} INFO - [2025-10-10T08:58:36.983+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T08:58:37.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T08:58:37.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.155 seconds
[2025-10-10T09:01:19.814+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:01:19.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:01:19.838+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:01:19.836+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:01:19.922+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:01:19.910+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:01:19.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:01:20.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.248 seconds
[2025-10-10T09:01:50.767+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:01:50.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:01:50.785+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:01:50.781+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:01:50.858+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:01:50.840+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:01:50.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:01:51.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.297 seconds
[2025-10-10T09:02:21.786+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:02:21.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:02:21.801+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:02:21.800+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:02:21.872+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:02:21.858+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:02:21.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:02:21.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.189 seconds
[2025-10-10T09:02:52.200+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:02:52.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:02:52.220+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:02:52.218+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:02:52.334+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:02:52.312+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:02:52.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:02:52.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.225 seconds
[2025-10-10T09:03:22.841+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:03:22.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:03:22.856+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:03:22.855+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:03:22.938+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:03:22.918+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:03:22.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:03:23.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.200 seconds
[2025-10-10T09:03:53.660+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:03:53.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:03:53.688+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:03:53.685+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:03:53.818+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:03:53.797+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:03:53.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:03:53.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.258 seconds
[2025-10-10T09:04:24.349+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:04:24.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:04:24.358+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:04:24.358+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:04:24.397+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:04:24.388+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:04:24.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:04:24.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.119 seconds
[2025-10-10T09:04:55.589+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:04:55.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:04:55.609+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:04:55.608+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:04:55.670+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:04:55.657+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:04:55.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:04:55.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.179 seconds
[2025-10-10T09:05:26.646+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:05:26.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/churn_pipeline.py for tasks to queue
[2025-10-10T09:05:26.667+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:05:26.665+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:05:26.780+0000] {logging_mixin.py:190} INFO - [2025-10-10T09:05:26.756+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/churn_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/churn_pipeline.py", line 11, in <module>
    from src.EDA import run_eda
ModuleNotFoundError: No module named 'src'
[2025-10-10T09:05:26.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/churn_pipeline.py
[2025-10-10T09:05:26.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/churn_pipeline.py took 0.285 seconds
